Config:
  max-range: 10
  update-checker: true
  default-range: 3
  owner-only-change-range: true
  proximity-sensor-name: Redstone Proximity Sensor
  not-proximity-sensor-name: NOT Redstone Proximity Sensor
  proximity-range-notify-text: Proximity Range
Redstones: {}
