rps:
  maxRange: 20
  defaultRange: 5
  defaultownerOnlyEdit: true
  defaultInverted: false
  defaultownerOnlyTrigger: false
  defaultPlayerEntityTrigger: true
  defaultHostileEntityTrigger: false
  defaultPeacefulEntityTrigger: false
  defaultDroppedItemsTrigger: false
  defaultInvisibleEntityTrigger: false