name: RedstoneProximitySensor
main: com.ugleh.redstoneproximitysensor.RedstoneProximitySensor
description: A Sensor can be crafted that has proximity effects.
author: Ugleh
softdepend: [Towny, GriefPrevention, LegacyFactions]
version: 2.4.3
api-version: 1.13
permissions:
  rps.create:
    description: Permission to craft proximity sensors.
    default: true
  rps.debug:
    description: Permission to view debug text.
    default: false
  rps.list:
    description: Permission to use list command.
    default: true
  rps.list.player:
    description: Permission to use list command with player arg.
    default: op
  rps.place:
    description: Permission to place down proximity sensors.
    default: true
  rps.invisible:
    description: Permission given to prevent triggering of RPS.
    default: op
  rps.menu:
    description: Permission to use RPS GUI Menu.
    default: true
  rps.button_invertpower:
    description: Permission to use said button.
    default: true
  rps.button_range:
    description: Permission to use said button.
    default: true
  rps.button_copy:
    description: Permission to use said button.
    default: true
  rps.button_paste:
    description: Permission to use said button.
    default: true
  rps.button_owneronlyedit:
    description: Permission to use said button.
    default: true
  rps.button_ownertrigger:
    description: Permission to use said button.
    default: true
  rps.button_playerentitytrigger:
    description: Permission to use said button.
    default: true
  rps.button_hostileentitiestrigger:
    description: Permission to use said button.
    default: true
  rps.button_peacefulentitiestrigger:
    description: Permission to use said button.
    default: true
  rps.button_droppeditemtrigger:
    description: Permission to use said button.
    default: true
  rps.button_invisibleentitiestrigger:
    description: Permission to use said button.
    default: true
  rps.button_projectiletrigger:
    description: Permission to use said button.
    default: true
  rps.button_vehicletrigger:
    description: Permission to use said button.
    default: true
  rps.button_townytrigger:
    description: Permission to use Towny Addon.
    default: true
  rps.button_gptrigger:
    description: Permission to use GP Addon.
    default: true
  rps.button_lfactiontrigger:
    description: Permission to use LegacyFactions Addon
    default: true
commands:
  rps:
    description: The admin command for RPS control.
    permission: rps.admin
    default: op
  rpslist:
    description: The command to view your RPS sensors.
    permission: rps.list
    default: true
  ignorerps:
    description: The command to toggle ignore the RPS or not.
    permission: rps.invisible
    default: op