name: RedstoneSensor
version: 1.6
author: Ugleh
main: com.ugleh.redstonesensor.RedstoneSensor
description: Create redstone proximity sensor torches that creates a redstone current when a player is in range.
permissions:
  redstonesensor.*:
    description: Gives access to all Redstone Sensor commands
    children:
      redstonesensor.use: true
  redstonesensor.use:
    description: Gives access to use the plugin. Only permission, for now.
    default: true